version: '3.0'

networks:
  app-network: 

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network

  php-fpm:
    image: php:8.1-fpm
    container_name: php-fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./www:/data/www
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql:mysql
      - redis:redis
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    links:
      - php-fpm:php-fpm
    volumes:
      - ./www:/data/www
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx:rw
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network