version: '3.0'

networks:
  app-network: 

services:
  my_db:
    image: mysql:5.7
    container_name: my_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    networks:
      - app-network

  my_redis:
    image: redis
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network

  my_php:
    image: php:8.1-fpm
    container_name: my_php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
      - ./configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - my_db:mysql
      - my_redis:redis
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network

  my_nginx:
    image: nginx
    container_name: my_nginx
    restart: always
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    links:
      - my_php:php
    volumes:
      - ./www:/usr/share/nginx/html
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx:rw
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network