version: '3.0'
services:
  mysql:
    container_name: docker-mysql
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ../../config/mysql:/etc/mysql/conf.d:ro
      - ../../logs/mysql:/var/log/mysql:ro
      - ../../data/mysql:/var/lib/mysql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci