version: '3.0'

services:
  mysql:
    container_name: docker-mysql
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./conf.d:/etc/mysql/conf.d:rw
      - ./logs/mysql:/var/log/mysql:rw
      - ./data/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci