version: '3.0'

services:
  nginx:
    container_name: docker-nginx
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
        - ../../www:/usr/share/nginx/html:rw
        - ./configs/nginx/ngixn.conf:/etc/nginx/ngixn.conf
        - ./configs/nginx/conf.d:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
    command: nginx -g 'daemon off;'