version: '3.0'
services:
  nginx:
    container_name: docker-nginx
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=1.17
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
        - ../../www:/data/www:ro
        - ./ngixn.conf:/etc/nginx/ngixn.conf:ro
        - ./conf.d:/etc/nginx/conf.d:ro
        - ./logs:/var/log/nginx
    command: nginx -g 'daemon off;'