version: '3.0'
services:
  nginx:
    container_name: docker-nginx
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=1.17
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
        - ../../www:/data/www:ro
        - ../../config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ../../config/nginx/conf.d:/etc/nginx/conf.d
        - ../../logs/nginx:/var/log/nginx
    command: nginx -g 'daemon off;'