version: '3.0'

services:
    redis:
        container_name: docker-redis
        build:
          context: ./
          dockerfile: Dockerfile
          args:
              - REDIS_VERSION=6.0.5
        restart: always
        ports:
        - "6379:6379"
        volumes:
        - ./conf.d/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./data:/data:ro
        - ./logs:/logs:ro
        command: redis-server /usr/local/etc/redis/redis.conf